### PR TITLE
Honda proto3 hand

### PR DESCRIPTION
**Pull request by mebbaid**
Added support for the new honda proto3 hand.

### CODE REVIEW

**Comment by mebbaid** [comment]
Ciao @traversaro , I opened this PR that resolved the issue https://github.com/ami-iit/projection_ami-honda/issues/53.
The PR is opened against the ami fork instead of the robotology origin since we will decide after the update meeting with honda if we can put their coupling laws for the new hand on a public repo or if it is enough to keep it in the ami fork,

**Comment by traversaro** [comment]
> Ciao @traversaro , I opened this PR that resolved the issue [ami-iit/projection_ami-honda#53](https://github.com/ami-iit/projection_ami-honda/issues/53).

Ok! So probably we can make the fork private for now?

**Comment by mebbaid** [comment]
> Ok! So probably we can make the fork private for now?

For me yes. I am not able to change the visibility of this fork, so can you do it. thanks !

**Comment by mebbaid** [comment]
Thanks, closed in favor of https://github.com/ami-iit/gazebo-yarp-plugins-honda/pull/1

**Pull request closed without merging**
